# redis配置，以下有默认配置的也可以使用默认配置
spring:
  redis:
    host: 39.99.195.107
    port: 6379
    password: 123456
  jedis:
    pool:
      max-active: 100
      max-wait: 100
      max-idle: 20
      min-idle: 10
  timeout: 300
