# redis配置，以下有默认配置的也可以使用默认配置
spring:
  redis:
    host: 192.168.164.142
    port: 6379
    password: 123456
  pool:
    max-active: 100
    max-wait: 100
    max-idle: 20
    min-idle: 10
  timeout: 300
