server:
  port: 7777
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /@project.artifactId@

# elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
spring:
  data:
    elasticsearch:
      cluster-nodes: 39.99.195.107
      cluster-port: 9200
      username: docker-cluster
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/gd_blog?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
      #更新或者创建数据表结构
      #ddl-auto: update
      ddl-auto: none
      #控制台显示SQL
      show-sql: false
      #使创建Unique最大能超过1000字符
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      #防止failed to lazily initialize a collection of XXXX
      servlet:
        content-type: text/html
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册